CREATE TABLE "profiles" (
	"id" uuid PRIMARY KEY NOT NULL,
	"email" text NOT NULL,
	"full_name" text,
	"avatar_url" text,
	"role" text DEFAULT 'user' NOT NULL,
	"updated_at" timestamp DEFAULT now(),
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "agendas" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"title" text NOT NULL,
	"urgency" varchar(50),
	"deadline" timestamp,
	"priority" text,
	"director" text,
	"initiator" text,
	"support" text,
	"contact_person" text,
	"position" text,
	"phone" text,
	"legal_review" text,
	"risk_review" text,
	"compliance_review" text,
	"regulation_review" text,
	"recommendation_note" text,
	"proposal_note" text,
	"presentation_material" text,
	"supporting_documents" jsonb DEFAULT '[]'::jsonb,
	"not_required_files" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"status" text DEFAULT 'Draft' NOT NULL,
	"kepdir_sirkuler_doc" text,
	"grc_doc" text,
	"cancellation_reason" text,
	"execution_date" date,
	"start_time" time,
	"end_time" varchar(50) DEFAULT 'Selesai',
	"meeting_method" varchar(50),
	"meeting_location" text,
	"meeting_link" text,
	"meeting_type" text DEFAULT 'RADIR',
	"meeting_number" varchar(50),
	"meeting_year" varchar(4),
	"pimpinan_rapat" jsonb DEFAULT '[]'::jsonb,
	"attendance_data" jsonb DEFAULT '{}'::jsonb,
	"guest_participants" jsonb DEFAULT '[]'::jsonb,
	"executive_summary" text,
	"considerations" text,
	"risalah_body" text,
	"catatan_rapat" text,
	"arahan_direksi" jsonb DEFAULT '[]'::jsonb,
	"meeting_decisions" jsonb DEFAULT '[]'::jsonb,
	"dissenting_opinion" text,
	"meeting_status" text DEFAULT 'PENDING',
	"risalah_group_id" uuid DEFAULT gen_random_uuid(),
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
